/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/authenticated/settings/index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/authenticated/plans/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/authenticated/payments/index'
import { Route as AuthenticatedOverviewIndexRouteImport } from './routes/authenticated/overview/index'
import { Route as AuthenticatedMembersIndexRouteImport } from './routes/authenticated/members/index'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/authenticated/insights/index'
import { Route as AuthenticatedEntryLogsIndexRouteImport } from './routes/authenticated/entry-logs/index'
import { Route as AuthenticatedPlansPlan_idRouteImport } from './routes/authenticated/plans/$plan_id'
import { Route as AuthenticatedMembersMember_idRouteImport } from './routes/authenticated/members/$member_id'
import { Route as AuthenticatedEntryLogsLog_idRouteImport } from './routes/authenticated/entry-logs/$log_id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/authenticated',
  path: '/authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOverviewIndexRoute =
  AuthenticatedOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersIndexRoute =
  AuthenticatedMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/insights/',
    path: '/insights/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntryLogsIndexRoute =
  AuthenticatedEntryLogsIndexRouteImport.update({
    id: '/entry-logs/',
    path: '/entry-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlansPlan_idRoute =
  AuthenticatedPlansPlan_idRouteImport.update({
    id: '/plans/$plan_id',
    path: '/plans/$plan_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMembersMember_idRoute =
  AuthenticatedMembersMember_idRouteImport.update({
    id: '/members/$member_id',
    path: '/members/$member_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEntryLogsLog_idRoute =
  AuthenticatedEntryLogsLog_idRouteImport.update({
    id: '/entry-logs/$log_id',
    path: '/entry-logs/$log_id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/entry-logs/$log_id': typeof AuthenticatedEntryLogsLog_idRoute
  '/authenticated/members/$member_id': typeof AuthenticatedMembersMember_idRoute
  '/authenticated/plans/$plan_id': typeof AuthenticatedPlansPlan_idRoute
  '/authenticated/entry-logs/': typeof AuthenticatedEntryLogsIndexRoute
  '/authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/entry-logs/$log_id': typeof AuthenticatedEntryLogsLog_idRoute
  '/authenticated/members/$member_id': typeof AuthenticatedMembersMember_idRoute
  '/authenticated/plans/$plan_id': typeof AuthenticatedPlansPlan_idRoute
  '/authenticated/entry-logs': typeof AuthenticatedEntryLogsIndexRoute
  '/authenticated/insights': typeof AuthenticatedInsightsIndexRoute
  '/authenticated/members': typeof AuthenticatedMembersIndexRoute
  '/authenticated/overview': typeof AuthenticatedOverviewIndexRoute
  '/authenticated/payments': typeof AuthenticatedPaymentsIndexRoute
  '/authenticated/plans': typeof AuthenticatedPlansIndexRoute
  '/authenticated/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/authenticated/entry-logs/$log_id': typeof AuthenticatedEntryLogsLog_idRoute
  '/authenticated/members/$member_id': typeof AuthenticatedMembersMember_idRoute
  '/authenticated/plans/$plan_id': typeof AuthenticatedPlansPlan_idRoute
  '/authenticated/entry-logs/': typeof AuthenticatedEntryLogsIndexRoute
  '/authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/authenticated/members/': typeof AuthenticatedMembersIndexRoute
  '/authenticated/overview/': typeof AuthenticatedOverviewIndexRoute
  '/authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/entry-logs/$log_id'
    | '/authenticated/members/$member_id'
    | '/authenticated/plans/$plan_id'
    | '/authenticated/entry-logs/'
    | '/authenticated/insights/'
    | '/authenticated/members/'
    | '/authenticated/overview/'
    | '/authenticated/payments/'
    | '/authenticated/plans/'
    | '/authenticated/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/entry-logs/$log_id'
    | '/authenticated/members/$member_id'
    | '/authenticated/plans/$plan_id'
    | '/authenticated/entry-logs'
    | '/authenticated/insights'
    | '/authenticated/members'
    | '/authenticated/overview'
    | '/authenticated/payments'
    | '/authenticated/plans'
    | '/authenticated/settings'
  id:
    | '__root__'
    | '/'
    | '/authenticated'
    | '/login'
    | '/authenticated/entry-logs/$log_id'
    | '/authenticated/members/$member_id'
    | '/authenticated/plans/$plan_id'
    | '/authenticated/entry-logs/'
    | '/authenticated/insights/'
    | '/authenticated/members/'
    | '/authenticated/overview/'
    | '/authenticated/payments/'
    | '/authenticated/plans/'
    | '/authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated': {
      id: '/authenticated'
      path: '/authenticated'
      fullPath: '/authenticated'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authenticated/settings/': {
      id: '/authenticated/settings/'
      path: '/settings'
      fullPath: '/authenticated/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/plans/': {
      id: '/authenticated/plans/'
      path: '/plans'
      fullPath: '/authenticated/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/payments/': {
      id: '/authenticated/payments/'
      path: '/payments'
      fullPath: '/authenticated/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/overview/': {
      id: '/authenticated/overview/'
      path: '/overview'
      fullPath: '/authenticated/overview/'
      preLoaderRoute: typeof AuthenticatedOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/members/': {
      id: '/authenticated/members/'
      path: '/members'
      fullPath: '/authenticated/members/'
      preLoaderRoute: typeof AuthenticatedMembersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/insights/': {
      id: '/authenticated/insights/'
      path: '/insights'
      fullPath: '/authenticated/insights/'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/entry-logs/': {
      id: '/authenticated/entry-logs/'
      path: '/entry-logs'
      fullPath: '/authenticated/entry-logs/'
      preLoaderRoute: typeof AuthenticatedEntryLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/plans/$plan_id': {
      id: '/authenticated/plans/$plan_id'
      path: '/plans/$plan_id'
      fullPath: '/authenticated/plans/$plan_id'
      preLoaderRoute: typeof AuthenticatedPlansPlan_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/members/$member_id': {
      id: '/authenticated/members/$member_id'
      path: '/members/$member_id'
      fullPath: '/authenticated/members/$member_id'
      preLoaderRoute: typeof AuthenticatedMembersMember_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/authenticated/entry-logs/$log_id': {
      id: '/authenticated/entry-logs/$log_id'
      path: '/entry-logs/$log_id'
      fullPath: '/authenticated/entry-logs/$log_id'
      preLoaderRoute: typeof AuthenticatedEntryLogsLog_idRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedEntryLogsLog_idRoute: typeof AuthenticatedEntryLogsLog_idRoute
  AuthenticatedMembersMember_idRoute: typeof AuthenticatedMembersMember_idRoute
  AuthenticatedPlansPlan_idRoute: typeof AuthenticatedPlansPlan_idRoute
  AuthenticatedEntryLogsIndexRoute: typeof AuthenticatedEntryLogsIndexRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
  AuthenticatedMembersIndexRoute: typeof AuthenticatedMembersIndexRoute
  AuthenticatedOverviewIndexRoute: typeof AuthenticatedOverviewIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedEntryLogsLog_idRoute: AuthenticatedEntryLogsLog_idRoute,
  AuthenticatedMembersMember_idRoute: AuthenticatedMembersMember_idRoute,
  AuthenticatedPlansPlan_idRoute: AuthenticatedPlansPlan_idRoute,
  AuthenticatedEntryLogsIndexRoute: AuthenticatedEntryLogsIndexRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
  AuthenticatedMembersIndexRoute: AuthenticatedMembersIndexRoute,
  AuthenticatedOverviewIndexRoute: AuthenticatedOverviewIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
